config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :reviews

  resources :fun_comments

  resources :authors

  resources :users

  resources :nodes

  root 'welcome#index'

end

app/models/fun_comment.rb
class FunComment < ActiveRecord::Base
end

app/controllers/fun_comments_controller.rb
class FunCommentsController < ApplicationController
  before_action :set_fun_comment, only: [:show, :edit, :update, :destroy]

  # GET /fun_comments
  # GET /fun_comments.json
  def index
    @fun_comments = FunComment.all
  end

  # GET /fun_comments/1
  # GET /fun_comments/1.json
  def show
  end

  # GET /fun_comments/new
  def new
    @fun_comment = FunComment.new
  end

  # GET /fun_comments/1/edit
  def edit
  end

  # POST /fun_comments
  # POST /fun_comments.json
  def create
    @fun_comment = FunComment.new(fun_comment_params)

    respond_to do |format|
      if @fun_comment.save
        format.html { redirect_to @fun_comment, notice: 'Fun comment was successfully created.' }
        format.json { render :show, status: :created, location: @fun_comment }
      else
        format.html { render :new }
        format.json { render json: @fun_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fun_comments/1
  # PATCH/PUT /fun_comments/1.json
  def update
    respond_to do |format|
      if @fun_comment.update(fun_comment_params)
        format.html { redirect_to @fun_comment, notice: 'Fun comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fun_comment }
      else
        format.html { render :edit }
        format.json { render json: @fun_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fun_comments/1
  # DELETE /fun_comments/1.json
  def destroy
    @fun_comment.destroy
    respond_to do |format|
      format.html { redirect_to fun_comments_url, notice: 'Fun comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fun_comment
      @fun_comment = FunComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fun_comment_params
      params.require(:fun_comment).permit(:author_no, :name, :body, :deleted)
    end
end

app/helpers/fun_comments_helper.rb
module FunCommentsHelper
end

app/views/fun_comments/_form.html.erb
<%= form_for(@fun_comment) do |f| %>
  <% if @fun_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fun_comment.errors.count, "error") %> prohibited this fun_comment from being saved:</h2>

      <ul>
      <% @fun_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_no %><br>
    <%= f.number_field :author_no %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fun_comments/edit.html.erb
<h1>Editing fun_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fun_comment %> |
<%= link_to 'Back', fun_comments_path %>

app/views/fun_comments/index.html.erb
<h1>Listing fun_comments</h1>

<table>
  <thead>
    <tr>
      <th>Author no</th>
      <th>Name</th>
      <th>Body</th>
      <th>Deleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fun_comments.each do |fun_comment| %>
      <tr>
        <td><%= fun_comment.author_no %></td>
        <td><%= fun_comment.name %></td>
        <td><%= fun_comment.body %></td>
        <td><%= fun_comment.deleted %></td>
        <td><%= link_to 'Show', fun_comment %></td>
        <td><%= link_to 'Edit', edit_fun_comment_path(fun_comment) %></td>
        <td><%= link_to 'Destroy', fun_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fun comment', new_fun_comment_path %>

app/views/fun_comments/new.html.erb
<h1>New fun_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', fun_comments_path %>

app/views/fun_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author no:</strong>
  <%= @fun_comment.author_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @fun_comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @fun_comment.body %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @fun_comment.deleted %>
</p>

<%= link_to 'Edit', edit_fun_comment_path(@fun_comment) %> |
<%= link_to 'Back', fun_comments_path %>