config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :reviews

  resources :fun_comments

  resources :authors

  resources :users

  resources :nodes

  root 'welcome#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    args = {
      # :include => {
      #   :user => {
      #     :only => [ :id, :email, :username ]
      #   }
      # },
      :except => [ :created_at, :updated_at ]
    }
    dat = {
      :authors => @authors,
      :success => true,
    }
    case params[:format]
    when 'yaml' then render :text => dat.to_yaml(:include => :user), :content_type => 'text/yaml'
    else
      respond_to do |format|
        format.html
        format.json { render(:json => dat.to_json(args)) }
        format.xml  { render(:xml  => dat.to_xml(args))  }
      end
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:user_id, :name, :birth, :address, :ctype, :photo)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select :birth %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :ctype %><br>
    <%= f.text_field :ctype %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Birth</th>
      <th>Address</th>
      <th>Ctype</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.user %></td>
        <td><%= author.name %></td>
        <td><%= author.birth %></td>
        <td><%= author.address %></td>
        <td><%= author.ctype %></td>
        <td><%= author.photo %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @author.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @author.birth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @author.address %>
</p>

<p>
  <strong>Ctype:</strong>
  <%= @author.ctype %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @author.photo %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>